# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cj9ZF144FvOnp-oq_Y1VsfUZAj7TXN6
"""

from keras.models import load_model
import pickle
import pandas as pd
import numpy as np
import sys
from catboost import CatBoostClassifier
from sklearn.preprocessing import MinMaxScaler
from keras.models import Model

def eval(data):
    
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
        
    with open("scaler.sav", "rb") as f:
        scaler = pickle.load(f)
        
    model2 = load_model('model.h5')
    
      
    features = pd.DataFrame(data=np.array(data),    
             columns=[str(i) for i in range(30)])
    
    first_predict = model.predict_proba(features)[:,1]
    
    scaled_features = scaler.transform(features)
    
    sec_predict = model2.predict(scaled_features)
    
    features['first'] = first_predict
    features['sec'] = sec_predict
    features['final'] = (features['first'] +features['sec'] )/2

    final_predict = np.array(features['final'])
    
    return final_predict